# Generated by Django 4.0.1 on 2022-01-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_employee_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='department',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='position',
            new_name='title',
        ),
        migrations.AddField(
            model_name='department',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='position',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
